export const INSURANCE_COMPANIES = [
  "PT Asuransi Central Asia (ACA)",
  "PT Asuransi Allianz Utama Indonesia",
  "PT Asuransi Adira Dinamika (Adira Insurance)",
  "PT Asuransi Sinar Mas",
  "PT BRI Asuransi Indonesia (BRINS)",
  "PT Avrist General Insurance",
  "PT China Taiping Insurance Indonesia",
  "PT FPG Insurance Indonesia",
  "PT Asuransi AIG Indonesia",
  "PT Asuransi Jasa Indonesia (Jasindo)",
  "PT Asuransi Wahana Tata",
  "PT Asuransi Multi Artha Guna Tbk (MAG)",
  "PT Asuransi Tokio Marine Indonesia",
  "PT Asuransi AXA Indonesia",
  "PT Asuransi MSIG Indonesia",
  "PT Asuransi QBE Pool Indonesia",
  "PT Asuransi Raksa Pratikara",
  "PT Asuransi Dayin Mitra Tbk",
  "PT Asuransi Himalaya Pelindung",
  "PT Asuransi Artarindo",
  "PT Asuransi Jasa Tania Tbk",
  "PT Asuransi Bangun Askrida",
  "PT Asuransi Ramayana Tbk",
  "PT Asuransi Tri Pakarta",
  "PT Asuransi Purna Artanugraha",
  "PT Asuransi Tugu Pratama Indonesia Tbk",
  "PT Asuransi Umum Mega",
  "PT Asuransi ASEI Indonesia",
  "PT Asuransi Intra Asia",
  "PT Asuransi Jasaraharja Putera",
  "PT Asuransi Mitra Maparya Tbk",
  "PT Asuransi Parolamas",
  "PT Asuransi Reliance Indonesia",
  "PT Asuransi Samsung Tugu",
  "PT Asuransi Victoria",
  "PT Asuransi Zurich Indonesia",
  "PT Asuransi Buana Independent",
  "PT Asuransi Central Asia Raya",
  "PT Asuransi Harta Aman Pratama Tbk",
  "PT Asuransi Jaya Proteksi",
  "PT Asuransi Kresna Mitra Tbk",
  "PT Asuransi Mega Pratama",
  "PT Asuransi Permata Indonesia",
  "PT Asuransi Raya",
  "PT Asuransi Recapital",
  "PT Asuransi Sinar Mas Syariah",
  "PT Asuransi Staco Mandiri",
  "PT Asuransi Tokio Marine Indonesia Syariah",
  "PT Asuransi Umum BCA",
  "PT Asuransi Wahana Tata Syariah",
  "PT Asuransi Zurich Indonesia Syariah",
  "PT Asuransi Adira Dinamika Syariah",
  "PT Asuransi Bintang, Tbk",
  "Sunday Insurance Indonesia",
  "PT Asuransi Astra Buana",
  "PT Asuransi MAXIMUS",
  "PT Great Eastern General Insurance Indonesia",
  "PT Asuransi Candi Utama",
  "PT Asta Kanti Insurance Broker",
  "Asuransi Sahabat",
  "PT Malacca Trust Wuwungan Insurance Indonesia",
  "DSR Broker",
  "PT Adi Antara Asia Broker",
  "PT MNC Insurance"
];
